server {
    listen 80;
    listen [::]:80;
    server_name faucet.lodechain.org;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        # Passing real IPs is crucial for rate limiting to work natively in express-rate-limit
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}