server {
    listen 80;
    listen [::]:80;
    server_name lodechain.org www.lodechain.org;

    root /var/www/lodechain.org;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}