# Define a rate limiting zone mapping client IP to a specific limit.
# 10m means 10 megabytes of memory for the state zone, rate=10r/s means 10 requests per second maximum per IP.
limit_req_zone $binary_remote_addr zone=rpc_limit:10m rate=10r/s;

server {
    listen 80;
    listen [::]:80;
    server_name rpc.lodechain.org;

    location / {
        # Apply the rate limiting zone
        limit_req zone=rpc_limit burst=20 nodelay;

        proxy_pass http://127.0.0.1:38081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}